version : '2'

services :

    node:
        image: node
        container_name: node
        tty: true
        depends_on :
          - postgres
        user: "node"
        volumes:
         - ./:/home/node/app
        ports:
         - "8081:8081"
        networks:
            integration6:
                ipv4_address: 172.18.0.3

    postgres:
        image: postgres
        container_name: postgres
        tty: true
        ports:
          - "5432:5432"
        expose:
          - "5432:5432"
        environment:
           POSTGRES_PASSWORD: Ephec123
        networks:
            integration6:
                ipv4_address: 172.18.0.2

networks:
    integration6:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.18.0.0/24
                  gateway: 172.18.0.1
